import Link from 'next/link';
import { requireBusiness } from '@/lib/services/context';
import { getCommissionReport } from '@/lib/services/commission-reports';
import { formatMinor } from '@/lib/domain/money';
import ApproveCommissionReport from '@/components/bdm/ApproveCommissionReport';

export const dynamic = 'force-dynamic';
export default async function CommissionReportPage({ params }: { params: { businessId: string; documentId: string } }) {
  const ctx = await requireBusiness(params.businessId, 'viewer'); const report = await getCommissionReport(ctx, params.documentId); const currency = report.document.currency || ctx.business.base_currency;
  const rows = report.lines.filter((line) => line.row_position > 0); const matched = rows.filter((line) => line.match_status === 'matched'); const approved = rows.filter((line) => line.match_status === 'approved'); const attention = report.lines.filter((line) => line.match_status === 'needs_attention');
  return <div className="bdm-page max-w-3xl space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><Link className="text-sm font-semibold text-muted" href={`/b/${ctx.businessId}/dashboard`}>← Travel dashboard</Link><p className="bdm-eyebrow mt-3">Commission report</p><h1 className="bdm-h1">{report.document.vendor || report.document.original_filename || 'Uploaded report'}</h1><p className="bdm-sub mt-1">{report.document.doc_date || 'Date not printed'} · {report.document.amount_minor == null ? 'Total not printed' : formatMinor(report.document.amount_minor, currency, { showMinor: true })}</p></div><a className="bdm-btn-secondary" target="_blank" rel="noreferrer" href={`/api/documents/${params.documentId}/view?businessId=${ctx.businessId}`}>View original report</a></header>
    {(matched.length > 0 || approved.length > 0) && <section><h2 className="bdm-h2 mb-2">{matched.length ? 'Matched' : 'Approved'}</h2><div className="space-y-2">{[...matched, ...approved].map((line) => <Row key={line.id} line={line} currency={currency} positive />)}</div></section>}
    {attention.length > 0 && <section><h2 className="bdm-h2 mb-2 text-negative">Needs attention</h2><div className="space-y-2">{attention.map((line) => <Row key={line.id} line={line} currency={currency} />)}</div></section>}
    {report.notOnReport.length > 0 && <section><h2 className="bdm-h2 mb-2">Not on this report</h2><p className="mb-2 text-sm text-muted">These bookings remain pending. Omission is not automatically an error.</p><div className="space-y-2">{report.notOnReport.map((booking) => <div key={booking.id} className="bdm-card flex justify-between gap-3 p-4"><strong>{booking.reference}</strong><span className="text-right"><strong className="bdm-num">{formatMinor(booking.commission_expected_minor - booking.commission_received_minor, booking.currency, { showMinor: true })}</strong><span className="bdm-badge-caution ml-3">PENDING</span></span></div>)}</div></section>}
    <ApproveCommissionReport businessId={ctx.businessId} documentId={params.documentId} count={matched.length} />
  </div>;
}

function Row({ line, currency, positive }: { line: { id: string; row_position: number; raw_booking_reference: string | null; reported_amount_minor: number | null; match_status: string; anomaly_code: string | null; anomaly_detail: string | null; booking: { commission_expected_minor: number; commission_received_minor: number } | null }; currency: string; positive?: boolean }) { const explanations: Record<string, string> = { UNKNOWN_BOOKING: 'Booking not found in Command.', AMOUNT_MISMATCH: 'Reported commission differs from the expected outstanding amount.', DUPLICATE_PAYMENT: 'This booking is already fully paid.', DUPLICATE_REPORT_ENTRY: 'This booking appears more than once in the report.', WRONG_CURRENCY: 'Report currency differs from the booking currency.', REPORT_TOTAL_MISMATCH: 'Printed report total differs from the extracted row total.', LUMP_SUM_MISMATCH: 'Attached deposit differs from the approved report total.' }; return <div className={`bdm-card p-4 ${positive ? 'border-positive/30' : 'border-negative/30'}`}><div className="flex justify-between gap-3"><div><p className="font-extrabold">{line.row_position === 0 ? 'Report total' : line.raw_booking_reference}</p><p className="mt-1 text-sm text-muted">{(line.anomaly_code && explanations[line.anomaly_code]) || line.anomaly_detail || (line.match_status === 'approved' ? 'Approved and paid' : 'Exact booking, currency and outstanding amount')}</p></div><div className="shrink-0 text-right"><p className="bdm-num font-extrabold">{line.reported_amount_minor == null ? '—' : formatMinor(line.reported_amount_minor, currency, { showMinor: true })}</p><span className={positive ? 'bdm-badge-positive' : 'bdm-badge-negative'}>{positive ? line.match_status.toUpperCase() : line.anomaly_code?.replaceAll('_', ' ')}</span></div></div>{line.booking && <p className="mt-2 text-xs text-muted">Expected outstanding {formatMinor(Math.max(0, line.booking.commission_expected_minor - line.booking.commission_received_minor), currency, { showMinor: true })}</p>}</div>; }
